services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./conf
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - backend
      - ai1
      - ai2

  ai1:
    container_name: ai1
    image: ai
    build:
      context: ../trippy-AI-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
  
  ai2:
    container_name: ai2
    image: ai
    build:
      context: ../trippy-AI-be
      dockerfile: Dockerfile
    ports:
      - "8080:8000"