name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: trippy/trippy-be
          stage: main
          yaml: |
          name: trippy-be
          app: node@16
          options:
            env:
              - name: NODE_ENV
                value: production
            ports: 3000
            build: npm run build
            start: npm run start:prod
          context:
            git:
              url: https://github.com/innovation-trippy/trippy-be.git
              branch: main
            preset: nest.js